baseurl = "/"
languageCode = "en-us"
title = "Cpise it!"

[params]
  description = "No idea what Ting is... @Knuckehead"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
    
    [[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 2
