baseurl = "/"
languageCode = "en-us"
title = "Drogheda Eats!"

[params]
  description = "Best of Drogheda"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
    
    [[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 2
